[phases.setup]
nixPkgs = [
  "chromium",
  "tesseract",
  "zlib",
  "libjpeg",
  "libpng",
  "libtiff",
  "libwebp",
  "freetype",
  "lcms2",
  "openjpeg",
  "nss",
  "nspr",
  "atk",
  "cups",
  "libdrm",
  "dbus",
  "libxkbcommon",
  "xorg.libX11",
  "xorg.libXcomposite",
  "xorg.libXdamage",
  "xorg.libXext",
  "xorg.libXfixes",
  "xorg.libXrandr",
  "mesa",
  "expat",
  "xorg.libxcb",
  "pango",
  "cairo",
  "alsa-lib"
]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "python bot.py"
